- name: Install CentOS repository files
  become: yes
  template:
    dest: "/{{ item }}"
    group: root
    mode: 0644
    owner: root
    src: "{{ item }}.j2"
  with_items:
    - etc/yum.repos.d/CentOS-Base.repo
    - etc/yum.repos.d/epel.repo
  notify:
    - Update yum cache
