- name: Install CentOS repository files
  become: yes
  template:
    dest: "/{{ item }}"
    group: root
    mode: 0644
    owner: root
    src: "{{ item }}.j2"
  with_items:
    - etc/yum.repos.d/CentOS-Base.repo
    - etc/yum.repos.d/epel.repo
  notify:
    - Update yum cache

# http://dnf.readthedocs.io/en/latest/conf_ref.html#options-for-both-main-and-repo
# deltarpm is useful when the bottleneck is the network throughput.
# It also requires additional drpm packages to be hosted by the mirrors which
# is not done by default.
- name: Disable deltrarpm
  become: yes
  ini_file:
    path: /etc/yum.conf
    section: main
    option: deltarpm
    value: 0
