---
- name: Start network appliance
  command: "/home/zuul/output/{{ platform }}/run_{{ platform }}.sh"

- name: Run ansible-test network-integration
  command: "{{ ansible_path }}/test/runner/ansible-test network-integration {{ nos }}_.* --inventory /home/zuul/{{ platform }}/inventory --continue-on-error"
