---
- name: Start network appliance
  command: "./run_{{ platform }}.sh"
  args:
    chdir: "/home/zuul/output/{{ platform }}"
  async: 7200
  poll: 0

- name: Run ansible-test network-integration
  command: "{{ ansible_path }}/test/runner/ansible-test network-integration {{ nos }}_.* --inventory /home/zuul/output/{{ platform }}/inventory --continue-on-error"
