- hosts: all
  tasks:
    # NOTE(pabelanger): We run this role in its own play to ensure unbound is
    # restarted before proceeding with any other role. This is because we use
    # notify / handler to restart the unbound service. With ansible notify
    # actions are triggered at the end of each block of tasks in a play.
    - name: Run configure-unbound role
      include_role:
        name: configure-unbound

    - name: Run validate-host role
      include_role:
        name: validate-host
